### ISSUE TITLE
power flow algorithm in parallel

### ISSUE THREAD

**Issue by liweiemma** [SanPen/fpotencia#8]
Dear Santiago,

My name is Wei. I am Francisco's colleague who asked you questions about running the test. 

We intend to run a power flow algorithm in parallel using both OpenMP and MPI. In one email you advised us that gauss seidel algorithm for power flow is highly parallelizable while newton raphson is not. We could not really figure out the reason behind. Could you please give us some hints?

One way to make gauss seidel algorithm (or newton raphson) run in parallel we can come up with is to split the whole admittance matrix into smaller ones that can be computed in multi-processors in parallel. So within each iteration, the states (bus voltage magnitudes and angles) will be acquired from multi-processors and updated together. 

We have not figured out other ways to make it parallel, especially with the fact that each iteration needs previous iteration's update. We are sincerely looking forwards to your suggestions. 

Best regards,
Wei

**Comment by SanPen** [comment]
Hi Wei,


All the power flow algorithms are iterative and most of them recursive. 
Certainly Gauss Seidel and Newton Raphson are recursive.

Gauss Seidel is parallelizable since every voltage is update 
independently from the others in every iteration, hence this can be done 
in parallel. The calculation of the currents that lead to the voltage 
update can be done in parallel as well.

(I remember a master thesis, but this shall illustrate the point: 
https://staff.najah.edu/sites/default/files/An_Efficient_Parallel_Gauss_Seidel_Algorithm_for_the_Solution_of_Load_Flow_Problems_0.pdf)

However, in Newton Raphson, the voltages are updated upon the results of 
the solution of a linear system (via LU, ILU, or any other) The 
parallelization of Newton raphson is much less straight forward, since 
the parallel efforts have to be focused in the linear algebra. The 
library OpenBlas is already parallel in that sense.

Not sure how you planned to split the Admittance matrix, but if it 
doesn't lead to a linear system, then the outcome is unlikely to be correct.

A suggestion, and by the way my initial aim with fPotencia, is to run 
concurrent power flows for different load states in parallel. Clearly 
the challenge is to send and collect object from the different threads. 
The direct application of this is Monte Carlo speed up, or time series 
simulation much faster.

I hope I have helped, best regards,

Santiago

**Comment by liweiemma** [comment]
Hi Santiago,

Thanks a lot for your quick reply. It helps a lot and the reference is very useful too. 

Best,
Wei

**Comment by fran-jo** [comment]
Hi!

> A suggestion, and by the way my initial aim with fPotencia, is to run
concurrent power flows for different load states in parallel. Clearly
the challenge is to send and collect object from the different threads.
The direct application of this is Monte Carlo speed up, or time series
simulation much faster.

We are working on the Jacobi_Solver.cpp for this (The easy one and we are already aware of its limitations). We are trying to implement OpenMP into it. First step is to paralleled the _for loop_ on the power flow calculations of each bus. Should we parallelise also the main while loop, for the number of iterations?

**Comment by SanPen** [comment]
The iterations loop cannot be paralelised, because the iterations order
cannot be altered.
In jacobi the second iteration depends on the first, the tbird on the
second and so on.
